-- phpMyAdmin SQL Dump
-- version 4.0.8
-- http://www.phpmyadmin.net
--
-- Host: sulley.cah.ucf.edu
-- Generation Time: Nov 14, 2013 at 01:58 PM
-- Server version: 5.5.34-0ubuntu0.12.04.1
-- PHP Version: 5.5.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `ar400093`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product` varchar(200) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `category` varchar(100) NOT NULL,
  `stock` int(11) NOT NULL,
  `cost` decimal(6,2) NOT NULL,
  `image` varchar(3000) NOT NULL,
  `rating` int(11) NOT NULL,
  `discount` decimal(6,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=47 ;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `product`, `description`, `category`, `stock`, `cost`, `image`, `rating`, `discount`) VALUES
(1, 'ORICO NCA-1513', 'Aluminum Laptop Cooling Pad with Dual 80MM Configurable Fans for 15.6 inch laptop', 'Laptop Cooling', 10, '17.99', 'img/products/laptopcooling/orico-nca-1513.jpg', 25, '0.00'),
(2, 'Gear Head CF3100SLV', 'Dual-cool notebook cooling pad', 'Laptop Cooling', 20, '6.99', 'img/products/laptopcooling/gear-head-cf3100slv.jpg', 25, '0.00'),
(3, 'Gear Head CF3000U-CP12', 'Duel-cool notebook cooling fan', 'Laptop Cooling', 40, '8.99', 'img/products/laptopcooling/gear-head-cf3000u-cp12.jpg', 25, '0.00'),
(4, 'Gear Head CFS4200BLK-CP4', '6 dual-cool notebook cooling stand. adjustable height design usb powered with included 3'' cable whisper quiet fan technology fits up to 15. 6 notebooks ', 'Laptop Cooling', 31, '8.99', 'img/products/laptopcooling/gear-head-cfs4200blk-cp4.jpg', 32, '8.10'),
(5, 'Gear Head Tri-Cool', 'Notebook cooling fan Model CF3600U', 'Laptop Cooling', 20, '16.99', 'img/products/laptopcooling/gear-head-tri-cool.jpg', 25, '0.00'),
(6, 'SYBA CL-NBK68019', 'Big Laptop Cooler Pad with Two Large 5" Fans Keep Notebook Computer Cool at All Time Model ', 'Laptop Cooling', 10, '16.99', 'img/products/laptopcooling/syba-cl-nbk68019.png', 25, '0.00'),
(7, 'Gear Head CF3300BLK', 'Dual-cool notebook cooling pad. Whisper quiet fan technology holds up to 17 notebooks built-in cord management system lightweight portable design', 'Laptop Cooling', 11, '29.99', 'img/products/laptopcooling/gear-head-cf3300blk.jpg', 25, '0.00'),
(8, 'USB Folding 2 Fan ', 'Laptop Notebook Cooling Pad Cooler', 'Laptop Cooling', 4, '5.99', 'img/products/laptopcooling/usb-folding-2-fan.jpg', 19, '5.40'),
(9, 'Cooler Master Notepal D-Lite', 'Notebook Cooler, support up to 15" notebook with 140mm fan ', 'Laptop Cooling', 7, '17.99', 'img/products/laptopcooling/cooler-master-notepal-d-lite.jpg', 25, '0.00'),
(10, '2Cool Black Walle', 'Chill Stand for Laptop. Sturdy aluminum frame keeps laptop cool. Unique, lightweight & compact wallet-like design', 'Laptop Cooling', 14, '18.99', 'img/products/laptopcooling/2cool-black-walle.jpg', 31, '0.00'),
(11, 'Cooler Master NotePal CMC3', 'Cooler Pad Support up to 15", with 200mm fan.  Silent 200mm fan to keep your laptop cool.\nErgonomic design for best viewing / typing angle.\nLightweight material for easy stow away.\nUSB extension port included.\nFront anti-slip holder ', 'Laptop Cooling', 10, '19.99', 'img/products/laptopcooling/coolermaster-notepal-cmc3.jpg', 37, '0.00'),
(12, 'Cooler Master NotePal I100 ', 'Laptop Cooling Pad  Ultra slim-only 23mm thick\nSilent 140mm fan to keep your laptop cool\nErgonomic design for excellent viewing/typing angles\nEasy cable management ', 'Laptop Cooling', 4, '20.99', 'img/products/laptopcooling/cooler-master-notepal-I100.jpg', 25, '0.00'),
(13, 'ENERMAX Case Fan', 'Fans are the main component of cooling every PC system and it''s the first line of defense against system overheat. With lower noise and long life, the ENERMAX Marathon fan offers a great choice for those wanting performance and quality at an unbeatable price. It features exclusive ENLOBAL bearing with magnetic-barometric design to run friction-free and noiseless. The nano-technology composite enables lowest abrasion and extreme durability. The detachable fan blade makes cleaning work a snap, so you can always keep your fan running at peak performance.', 'Case Fan', 10, '10.99', 'img/products/case-fan/enermax.jpg', 109, '0.00'),
(14, 'Bgears b-Blaster 120 Case Fan', 'bgears? b-Blaster 120 120mm case fan is a cost-efficient, high performance cooling solution for today''s desktop computers. The dual ball-bearing design extends the life span of the fan and keeps it spinning at around 2,000 RPM. It easily fits in a wide variety of desktop cases and yet is capable of delivering maximum 103 CFM of airflow.', 'Case Fan', 11, '12.99', 'img/products/case-fan/bgears.jpg', 35, '0.00'),
(15, 'MASSCOOL Case Cooling Fan', 'Protect your PC against the searing heat of everyday use. For cost-conscious shoppers and PC enthusiasts who want maximum bang for the buck, you?ll definitely want to make the MASSCOOL FD08025S1M4 Cooling Fan part of your cooling solution. The sleeve-bearing fan, operating with durable 80mm blades, safely ushers harmful thermal energy away from your PC?s sensitive components, at a rate of over 31 CFM (cubic feet per minute) during peak performance! This affordable model is a cinch to install, and the 28 dB generated at 2500 RPMs ? 10% means you?ll hardly notice it?s even in use! Besides keeping your system temps way down, this MASSCOOL case-compatible fan helps prevent dust and other particulate matter from building up inside your PC, which is vital to your system?s longevity. Whether you?re arming one desktop or several workstations, ensure you equip them with this first-rate cooling fan for solid protection and superior value.', 'Case Fan', 8, '4.99', 'img/products/case-fan/masscool.jpg', 26, '0.00'),
(16, 'Corsair Air Series AF140 Quiet Edition High Airflow Case Fan', 'The Air Series AF140 fans let you have it all. Eleven ultra-thin, custom-molded blades push ample air volume. Rubber corners dramatically reduce vibration. The advanced hydraulic bearing system is quiet and reliable, and you can customize the look with the three included colored rings. AF models performs  best in unrestricted spaces with at least 3cm of clearance, and they''re ideal for mounting at the rear or top of your PC case as exhaust fans for your PC''s motherboard and CPU, graphics accelerators, and other components that fill the case with heat. They work equally well as unrestricted intake fans for areas like side panels or bottom intakes. ', 'Case Fan', 15, '25.99', 'img/products/case-fan/corsair.jpg', 45, '0.00'),
(17, 'XIGMATEK eXTREME SILENT Series Case Fan with FCB (Fluid Circulative Bearing)', 'Optimal blade design enabling static pressure and torque and higher air flow, XSF series fan provides the reduction of noise and power consumption. With fluid circulative bearing, it can provide longer MTBF and outstanding performance. This package includes four XSF-F1252 case fans.', 'Case Fan', 12, '18.99', 'img/products/case-fan/xigmatek.jpg', 25, '0.00'),
(18, 'Rosewill Blue LEDs LED Case cooler', 'If you need to move more air than you can with an average 120mm fan, the Rosewill RFA-120-BL is your solution. Featuring a top speed of 2000RPM this fan pushes up to 74.48CFM. The sleeve bearing motor is designed for long life and the exterior mounted speed control makes it easy to adjust. The blue LEDs add a bit of atmosphere to your late night sessions.', 'Case Fan', 12, '8.99', 'img/products/case-fan/rosewill.jpg', 26, '0.00'),
(19, 'COOLER MASTER Blue LED Case cooler', 'R4 series fans offer a unity of maximum rotational speed and optimum airflow. Using a unique long-life sleeve bearing fan, the R4 series offers long life rating of 50,000 hours. R4 series fans perform at a maximum of 69CFM at 2000RPM.', 'Case Fan', 10, '11.99', 'img/products/case-fan/cooler-master.jpg', 20, '5.99'),
(20, 'XIGMATEK FCB (Fluid Circulative Bearing) Cooling System Crystal Series', 'The new Xigmatek CLF Crystal Series of 120mm system fans continues the company''s innovative design focus to provide advanced features and performance while maintaining excellent value to the end user. CLF Series is created with attention and detail, and not only does it look prestige from every angle it is manufactured with impeccable performance.', 'Case Fan', 9, '13.99', 'img/products/case-fan/xigmatek-fcb.jpg', 25, '0.00'),
(21, 'Fractal Design Silent Series', 'All new Silent Series R2 fans are equipped with high performance hydraulic bearings, increasing both fan performance and reliability. Each fan 60mm and larger is packaged with both 4 metal screws and 4 rubber screws to ensure maximum fan-mounting options. Using the rubber screws allows mechanical decoupling from the case itself, reducing vibrations and decreasing the noise level (40 and 50mm feature metal mounting screws only).', 'Case Fan', 7, '15.99', 'img/products/case-fan/fractal.jpg', 28, '14.40'),
(22, 'Noctua NF-F12 PWM 120mm Case Fan', 'Teaming up eleven stator guide vanes with a specially conceived seven blade impeller, the NF-F12''s Focused Flow system creates outstanding static pressure and focuses the airflow for superior performance on heatsinks and radiators. At the same time, a wide range of advanced aerodynamic design measures, second generation SSO-Bearings and Noctua''s new, custom designed PWM IC for fully automatic control guarantee astounding quietness of operation. The NF-F12 comes with modular cabling, integrated anti-vibration pads and two speed settings for full flexibility. Its commanding performance, exhaustive set of features and Noctua''s trusted premium quality make it an elite choice for use on air coolers, radiators and other pressure demanding applications.', 'Case Fan', 6, '30.99', 'img/products/case-fan/noctua.jpg', 25, '0.00'),
(23, 'SilenX EFX-08-12 80mm Effizio Quiet Case Fan', 'The ultimate in airflow to noise ratio, Effizio Quiet Fans are the only fans in the industry to be designed with silence and optimal airflow in mind. Smaller, domed motor hub, larger, more dramatic fan blade sweep area, no other fans on the market come even close in performance! There might be fans that offer more airflow or lower noise levels, but when it comes to a balance between the two, these fans can''t be beat, now with Japanese fluid dynamic bearings for ultra long life and reduced vibration.', 'Case Fan', 8, '10.99', 'img/products/case-fan/silenx.jpg', 25, '0.00'),
(24, 'COOLER MASTER Hyper TX3 RR-910-HTX3-G1 CPU Cooler', 'Cooler Master’s Hyper TX series has evolved with requirements of \nmainstream CPUs. The introduction of Hyper TX3 marks another milestone \nwith Cooler Master''s first-ever full compatibility - Intel LGA 1156 \nsocket. The Hyper TX3 also brings back the "original" direct contact \nheat-pipe design from Cooler Master.<br /><br />\n\n<strong>Superior Heat Dissipation The Cooler</strong><br />\nMaster Hyper TX3 features "heatpipe direct contact" technology for \nefficient heat conduction, plus high-density aluminum fins for maximum \nheat dissipation. The 92mm fan runs efficiently to deliver unparalleled \ncooling performance.<br /><br />\n                                    \n<strong>Expandable for a Second Fan</strong><br />\nAdd a 2nd cooling fan (optional) to the Cooler Master Hyper TX3 to achieve the best possible cooling performance!<br /><br />\n                                    \n<strong>PWM Function</strong><br />\nThe PWM function automatically adjusts fan speeds according to the CPU temperatu', 'Heatsink', 15, '19.99', 'img/products/heatsink/coolermaster_htx3.jpg', 25, '0.00'),
(25, 'Thermaltake Frio Universal CPU Cooler CLP0564', 'Thermaltake continues to bring innovative \nsolutions to CPU cooling challenges. The CLP0564 overclocking-ready and \nsix-core ready CPU cooler combines multiple features for optimal cooling\n of high-powered CPUs. The copper base rests directly against the chip \nto draw away damaging heat. Five seamlessly embedded heatpipes penetrate\n the cooling fin array above for optimal heat transfer and dissipation. \nDual fans, one on each side, move large amount of cooling air over the \nconvection fins at quiet noise level, and a fan control knob allows you \nto adjust the fan speed to reach a perfect balance between performance \nand noise.<br /><br />\nCompatible with Intel CPUs using LGA 1156 / 1366 /\n 775 socket and AMD CPUs in Socket AM2+ / AM2 / AM3 packaging, this \nversatile Thermaltake model was designed to work with just about every \nmodern desktop CPU. For ultra-cool protection and forward-thinking \nstyle, the Thermaltake Frio blows away the competition.<br /><br />\n\n<strong>Superior Heat Di', 'Heatsink', 9, '54.99', 'img/products/heatsink/thermaltake-clp0564.jpg', 25, '0.00'),
(26, 'COOLER MASTER Hyper 212 EVO RR-212E-20PK-R2 CPU Cooler', 'Unmatched performance for the value, these are the tenants that \nguided Cooler Master engineers when designing the Hyper 212 EVO. \nPatented Continuous Direct Contact (CDC) technology ensures that the \nheat pipes are free of barriers while drawing heat away from the \nprocessor. A PWM fan ensures that fan speed can be intelligently \ncontrolled to ensure that it only speeds up when more cooling is \nnecessary.<br /><br />\n\n<strong>HIGHLY EFFECTIVE COOLING</strong><br />\n4 x Direct Contact heat pipes with patented CDC (Continuous Direct Contact) technology draw heat away from the CPU quickly.<br /><br />\n\n<strong>USER & SYSTEM CONTROL OF FAN(S)</strong><br />\nA wide range PWM fan can be controlled by changing its settings \nthrough supported systems or software to suit your noise and performance\nneeds.<br /><br />\n    \n<strong>UNIVERSAL MOUNTING SOLUTION</strong><br />\nSupports the latest sockets from Intel and AMD.<br /><br />\n    \n<strong>QUICK SNAP FAN MOUNTING</strong><br />\nUtilize the ', 'Heatsink', 11, '39.99', 'img/products/heatsink/coolermaster-h212e.jpg', 17, '0.00'),
(27, 'Enermax ETS-T40-TB CPU Cooler', 'Enter the world of efficient cooling with the Enermax ETS-T40 CPU \r\ncooler! Enermax ETS-T40 delivers world leading thermal resistance \r\nperformance of 0.09 C/W thanks to the combination of three smart \r\ninnovations: Stack Effect Flow, Vortex Generator Flow and Vacuum Effect \r\nFlow. Its four 6mm high-performance heat pipes with HDT (Heatpipe Direct\r\n Touch) ensure rapid thermal conduction and eliminate CPU hotspot. Plus,\r\n the ETS-T40 features a unique T.B.Silence 12cm Twister Bearing PWM fan \r\nto provide persistent cooling efficiency and silence.<br /><br />                        \r\n                                \r\n<strong>Thermal Resistance Performance of 0.09 C/W</strong><br />\r\nThe world leading thermal resistance performance of 0.09 C/W is \r\nachieved by three smart innovations: Stack Effect Flow to enhance heat \r\ntransfer, Vortex Generator Flow to greatly increase air convection and \r\nunique air path creating high VEF (Vacuum Effect) to optimize the \r\nairflow.<br /><br />\r\n       ', 'Heatsink', 10, '34.99', 'img/products/heatsink/enermax-ets-t40-tb.jpg', 25, '0.00'),
(28, 'XIGMATEK Apache EP-CD903 CPU Cooler', 'Large dissipating area provides outstanding cooling performance.<br />\n\nPWM function to make cooler more efficient.<br />\n\nTransparent color fan blade.<br />', 'Heatsink', 11, '12.99', 'img/products/heatsink/xigmatek-apacheii-ep-cd903.jpg', 25, '0.00'),
(29, 'ARCTIC Freezer 7 Pro Rev. 2, CPU Cooler', 'Freezer 7 Pro Rev. 2 is a high performance CPU \ncooler for Intel and AMD. The heatsink features 6 heatpipes and 42 fins \nfor efficient heat dissipation. Thanks to the vibration absorption the \nfan is whisper-quiet even at full load.<br /><br />\n                    \n<strong>Efficient Cooling</strong><br />\n Featuring a 92 mm PWM fan and 6 heatpipes, the Freezer 7 Pro Rev.2 \noffers performance far beyond stock coolers and achieves 130 Watts \ncooling capacity. The unique heatsink design consists of 42 fins, which \nsignificantly enhances the heat dissipation performance.<br /><br />\n                            \n<strong>Minimum of Noise</strong><br />\nDue to the low noise impeller and the fan holder, the 92 mm fan of the \nFreezer 7 Pro Rev. 2 generates only 0.8 Sone at 2,500 rpm, which is \nextremely quiet for such performance. Controlled by PWM signal, the fan \nruns just the necessary speed at lowest noise level for maximum cooling \ncapacity.<br /><br />\n                            \n<strong', 'Heatsink', 16, '24.99', 'img/products/heatsink/arctic-freezer-7-pro-rev-2.png', 25, '0.00'),
(30, 'XIGMATEK Gaia SD1283 CPU Cooler', 'Gaia, adopted from Gaia the mother of earth, a goddess in Greek religion, the creator of all. This innovative and powerful cooler maintains your CPU at a stable low temperature.<br /><br />\n\n<strong>-Stable cool climate delivered to your CPU by the goddess herself.</strong><br />\nWe envisioned the Gaia to be just like mother earth, with the vision \nof creating a silent yet effective cooling environment for the CPU that \nreflects a peaceful rainforest ambience. Our engineers here at Xigmatek \nneeded to acquire a way to deliver the same remarkable effectiveness but\n with the aim of generating minimal sound pollution to simulate calm \ntranquilized surrounding.<br /><br />\n\n<strong>-We didn’t want to bring you just a cooler, We\nwanted to bring you an extraordinary cooler.</strong><br />\nOur team of highly experienced thermal engineers came up with an idea\n of inventing a more effective process to displace heat. We call this \nHeat-pipe Direct Touch Technology. To achieve this innovation we ', 'Heatsink', 12, '24.99', 'img/products/heatsink/xigmatek-gaia-sd1283.jpg', 25, '0.00'),
(31, 'MASSCOOL 8W553B1M3 CPU Cooler ', 'Step up from your stock cooling fan and heatsink \nto the MassCool 8W553B1M3. Designed for use with value-driven Intel \nprocessors including Core 2 Extreme, Core 2 Quad, Core 2 Duo, Pentium D \nas well as Celeron D. The aluminum base and heatsink provide the cooling\n performance you need to keep your desktop running at its peak.<br /><br />\n                   \n A long-life, ball bearing 90mm fan quickly draws \nheat away from the cooler''s fins at a lively 2,400rpm. The standard \n3-pin connector delivers broad compatibility to your motherboard. Keep \nyour CPU frosty in the hottest action with the Masscool 8W553B1M3!<br /><br />\n                    \n<strong>Excellent Cooling Performance</strong><br />\n The extruded aluminum fins optimize heat dissipation and the 90mm, \n2400RPM ball bearing fan delivers an air flow of up to 41.15 CFM for \nsupreme cooling performance.<br /><br />\n                            \n<strong>LGA 775 Compatible</strong><br />\nCompatible with the LGA 775 platform, the M', 'Heatsink', 7, '10.99', 'img/products/heatsink/masscool-8w553b1m3.jpg', 41, '0.00'),
(32, 'ZALMAN CNPS9500A-LED CPU Cooler ', 'For the PC-enthusiast who wants a desktop that \r\nlooks sizzling hot, yet stays remarkably cool, check out the Zalman \r\nCNP9500 LED CPU Cooler featuring a fan and heatsink!   This hi-tech \r\ncooling device gives your PC mesmerizing appeal with its gleaming copper\r\n finish and an eye-catching indigo blue LED light.<br /><br />\r\n\r\nThe copper heatsink saves space with an \r\narchitecturally sound 3-pipe system that effortlessly whisks heat away \r\nwith the help of the adjustable fan’s 92mm blades and 2 ball bearings. A\r\n FAN MATE 2 controller and cable are included with your durable Zalman \r\nCPU Cooler, allowing you to switch between an 18 dB/1350 RPM ''Silent'' \r\nmode and a 27 dB/2600 RPM ''Low Noise'' mode. For ultra-cool protection \r\nand aggressive styling, this device is the way to go.<br /><br />\r\n                    \r\n<strong>Unique Heatpipe Design</strong><br />\r\n Three innovative and curved heatpipes provide a heat transfer capacity \r\nmatching that of six heatpipe designs for maximum perfo', 'Heatsink', 18, '41.99', 'img/products/heatsink/zalman-cnps9500a-led.jpg', 25, '0.00'),
(33, 'XIGMATEK Dark Knight II SD1283 Night Hawk Edition CPU Cooler', 'The Xigmatek Stealth series\r\ncoolers make\r\nuse of advanced ceramic materials originally pioneered in the high-tech\r\naerospace and automotive industries. The ceramic coating features high\r\nstrength\r\nand light weight and is specially formulated for\r\nmaximum thermal\r\nconductivity making\r\nit well suited for use in extreme temperature environments.<br /><br />\r\n\r\n<strong>Xigmatek Dark Knight SD1283\r\nNighthawk\r\nEdition</strong><br />\r\n\r\nThe Xigmatek Dark Knight SD1283\r\nis the\r\nworld''s first enthusiast cooler to utilize a modern ceramic coating and\r\nwas the\r\nresult of Xigmatek thermal engineers thinking outside the box. Xigmatek''s\r\ninnovative\r\nuse of this space age material is not just for good looks - the ceramic\r\ncoating\r\nalong with Xigmatek''s patented HDT\r\ntechnology greatly\r\nincreases the efficiency of thermal transfer away from your CPU.<br /><br />\r\n\r\n-High Thermal Conductivity<br />\r\nThe\r\nincreased thermal conductivity of the ceramic coating rapidly absorbs\r\nand\r\nremoves heat from the ', 'Heatsink', 16, '49.99', 'img/products/heatsink/xigmatek-dark-knight-ii-sd1283-night-hawk-edition.jpg', 25, '0.00'),
(34, 'CORSAIR Hydro series H50 High Performance Liquid CPU Cooler', 'Your PC will run cooler and quieter when you replace your CPU’s standard heatsink with a Hydro Series H50. Installation is straightforward. If you can get to the back of your PC’s motherboard, you can install H50. All you’ll need is a screwdriver and you''ll be up and running in minutes. Maintenance is minimal thanks to closed-loop architecture and pre-filled coolant, which also deliver unmatched durability and reliability for worry-free use for years to come.', 'Water / Liquid Cooling', 10, '59.99', 'img/products/liquid/h50.jpg', 25, '0.00'),
(35, 'CORSAIR Hydro Series H60 (CW-9060007-WW) Water Cooler', 'Say goodbye to a stock air cooler, and upgrade from your bulky air cooler to the efficiency and simplicity of liquid CPU cooling. Enjoy better cooling performance and lower noise, and protect your investment in your CPU with the CORSAIR Hydro Series H60 water cooler. Installation is straightforward. If you can get to the back of your PC’s motherboard, you can install H60. All you’ll need is a screwdriver and you''ll be up and running in minutes. Maintenance is minimal thanks to closed-loop architecture and pre-filled coolant, which also deliver unmatched durability and reliability for worry-free use for years to come.', 'Water / Liquid Cooling', 5, '69.99', 'img/products/liquid/h60.jpg', 25, '0.00'),
(36, 'Thermaltake Water 3.0 Pro (CLW0223) Water Cooler', 'For a liquid cooler, enthusiasts not only looking for an easy and clean setup to efficiently calm the roaring CPU, more likely they also crave for the best low-maintenance solution. The new Thermaltake All-In-One LCS Water 3.0 Series is formed to support these desires of enthusiasts. Upgrade the simplicity of liquid CPU cooling to enjoy better cooling performance and protect the investment in the CPU as well.', 'Water / Liquid Cooling', 12, '89.99', 'img/products/liquid/thermaltake.jpg', 25, '0.00'),
(37, 'Antec Kuhler H2O 620 Liquid Cooling System', 'The Antec KUHLER H2O 620 delivers high-performance liquid cooling for your CPU in a quick, easy-to-install package. Unlike traditional liquid cooling systems, this self-contained unit comes pre-filled and requires no maintenance. The voltage-controlled 120mm fan and 3rd generation copper coldplate ensure efficient cooling, while the estimated 50,000 hour pump lifetime means this cooler is even likely to outlast the system it cools. Lastly, easy-bend flexible tubing allows the KUHLER H2O 620 to be installed in nearly any orientation. Take your PC''s Quiet Computing to the next level with liquid cooling performance at a price that rivals aftermarket air coolers.', 'Water / Liquid Cooling', 16, '57.99', 'img/products/liquid/620.jpg', 20, '0.00'),
(38, 'CORSAIR Hydro Series H100i Water Cooler', 'Say goodbye to a stock air cooler, and upgrade from your bulky air cooler to the efficiency and simplicity of liquid CPU cooling. Enjoy better cooling performance and lower noise, and protect your investment in your CPU with the CORSAIR Hydro Series H100i water cooler, which combines efficient cooling, simple installation, and intuitive management into an all-in-one solution. 240mm top-mounted radiator features twice the surface area of the H80i for even better performance, while 2x 120mm fans delivers efficient cooling at whisper quietness. Corsair Link allows you to monitor temperature and control lighting and fan speed on your screen. Quick and easy magnetic installation brackets make it easier than ever to upgrade to water cooling. Maintenance is minimal thanks to closed-loop architecture and pre-filled coolant, which also deliver unmatched durability and reliability for worry-free use for years to come.', 'Water / Liquid Cooling', 57, '109.99', 'img/products/liquid/h100.jpg', 25, '0.00'),
(39, 'Antec KUHLER H2O 920 Liquid Cooling System', 'The Antec KUHLER H2O 920 provides maximum-performance liquid cooling for your CPU in a quick, easy-to-install package. Unlike traditional liquid cooling systems, this self-contained unit comes prefilled and requires zero maintenance. The dual 120 mm Pulse Width Modulation (PWM) fans and 3rd generation copper coldplate ensure quiet, efficient cooling, while the 49 mm thick radiator is equipped to handle the highest performing CPUs on the market. Lastly, the included software helps you monitor and control the KUHLER H2O 920''s performance and allows you to customize its stylish RGB LED. Designed to unlock the maximum potential of your CPU, the Antec KUHLER H2O 920 delivers exceptional cooling when you need it the most.', 'Water / Liquid Cooling', 56, '116.99', 'img/products/liquid/920.jpg', 41, '0.00'),
(40, 'Enzotech HF-G1/4-38 Water Cooling Accessory', 'High Flow Fitting ', 'Water / Liquid Cooling', 102, '4.49', 'img/products/liquid/hf.jpg', 25, '0.00'),
(41, 'Enzotech BRCPS-G1/4-12-90 ID 1/2" Thread G1/4" Matt Black', 'Enzotech premium 90 degree rotary fitting is compatible with 1/2" ID tubing and G1/4" thread type.', 'Water / Liquid Cooling', 36, '8.99', 'img/products/liquid/brcps.jpg', 25, '0.00'),
(42, 'Enzotech BHF-G1/4-38 ID 3/8" Thread G1/4", Matt Black', 'Thread Type: G1/4"', 'Water / Liquid Cooling', 54, '4.99', 'img/products/liquid/bhf.jpg', 25, '0.00'),
(43, 'NZXT Kraken X60 RL-KRX60-01 280mm Ultra Performance Liquid CPU Cooler', 'NZXT Kraken series is the first premium all-in-one water coolers to provide both ease of use and functionality for PC enthusiasts. Kraken series X60 delivers unrivaled cooling performance with the included two NZXT FX-140 PWM fans and can offer upgraded cooling with the capacity to install an additional 2 more fans in a push-pull configuration. At the core of the cooler is a state-of-the-art pump attached to an all copper base. Bridging the 280mm radiator and pump is an extra-long 16” tubing and premium sleeved cables, easily installed into even in the largest chassis. It is the best closed loop water coolers on the market, you should not settle for anything less.', 'Water / Liquid Cooling', 36, '109.99', 'img/products/liquid/kraken.jpg', 25, '0.00');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
